### PR TITLE
Removed sidekiq startup from application container

### PR DESCRIPTION
**Pull request by lukaszraczylo**
Sidekiq now runs in separate container linked to redis one as requested
during last retrospective meeting.

### CODE REVIEW

**Comment by lukaszraczylo** [comment]
As per changes in https://github.com/ministryofjustice/pvb2-deploy/commit/458365d6e026e2a08edc844f0f915f8a8c508c29

**Comment by mloughran** [comment]
@lukaszraczylo Probably sidekiq shouldn't be daemonized (the `-d` flag) – this is unnecessary complexity and means that logs cannot simply be sent to STDOUT

**Comment by mloughran** [comment]
@lukaszraczylo ignore me – I see that this was changed in a future PR – just catching up on email!

**Comment by lukaszraczylo** [comment]
No worries :)

**Pull request merged**
