### PR TITLE
Use Rails's built-in Time stubbing

### PR DESCRIPTION
**Pull request by threedaymonk**
We don't need Timecop, so let's not add unnecessary dependencies.

http://api.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html

### CODE REVIEW

**Comment by threedaymonk** [comment]
@dan-palmer as you suggested!

**Comment by SteveMarshall** [comment]
Oooh, fancy! :tophat:

**Comment by dan-palmer** [comment]
Sweet! :)

**Comment by SteveMarshall** [comment]
Back… to the future!

**Pull request merged**
