### PR TITLE
Design iteration

### PR DESCRIPTION
**Pull request by chrishanes**
This will apply design amends based on designer feedback, mainly around the process page.

### CODE REVIEW

**Comment by chrishanes** [comment]
Before
before

**Comment by chrishanes** [comment]
After
after

**Comment by mloughran** [comment]
Generally looks good to me.

Is it potentially confusing that "the prisoner date of birth... have been verified" is included in the warning?

**Comment by chrishanes** [comment]
The verified content and warning isn't part of this PR, but I've seen at Brixton that the whole 'Verified' concept is confusing as they didn't know who or what has verified the info. Something to pick up with our content editor Shane.

**Comment by kyliemulholland** [comment]
@chrishanes looks good to me. Yes agreed, let's look at content for the validation errors separately. See https://trello.com/c/1dwdLFmU/380-prisoner-validation-staff-3

**Pull request merged**
